### ISSUE TITLE
communication plan

### ISSUE THREAD

**Issue by Gopiben** [HYF-Class19/agile-devlopment-group-3#2]

**Comment by Gopiben** [comment]
communication planning

**Comment by johnedelbi** [comment]
hello @Gopiben I see that you closed the issue but I can't see any pr for this issue so please would you write some info about it because there is no description

**Comment by talmurshidi** [comment]
This issue is empty and closed so it must removed from project board and milestone.

**Comment by Gopiben** [comment]
Ok i do today
